; generated by PrusaSlicer 2.9.4 on 2026-04-27 at 17:07:20 UTC

M73 P0 R0
M73 Q0 S0
M201 X1000 Y1000 Z200 E5000 ; sets maximum accelerations, mm/sec^2
M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm / sec
M204 S1250 T1250 ; sets acceleration (S) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E4.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec

G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S30 ; set extruder temp
M140 S30 ; set bed temp
G28 W ; home all without mesh bed level

G1 Z0.2 F720
G1 Y-3 F1000 ; go outside print area
G92 E0
M73 P7 R0
M73 Q7 S0

G92 E0
M221 S95

; Don't change E values below. Excessive value can damage the printer.

M907 E538 ; set extruder motor current
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion

;TYPE:Custom
; Filament-specific end gcode
G1 Z6.6 F720 ; Move print head up
M73 P87 R0
G1 X0 Y200 F3600 ; park
G1 Z54.6 F720 ; Move print head further up
M73 P92 R0
M73 Q92 S0
G4 ; wait
M221 S100 ; reset flow
M900 K0 ; reset LA

M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
M84 ; disable motors
; max_layer_z = 5.6
M73 P100 R0
M73 Q100 S0
M84 ; disable motors
